spring.datasource.url: jdbc:postgresql://localhost:5432/pg_test
spring.datasource.username: postgres
spring.datasource.password: admin
spring.datasource.driver-class-name: org.postgresql.Driver

springdoc:
  api-docs:
    enabled: true
