mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://135.251.45.53:3306/project4?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root@nsb

mybatis.configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server.port: 8083