spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql_test?serverTimezone=Asia/Shanghai
    username: root
    password: root

logging:
  level:
    com.example.demo.mapper: debug